[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
name = "commitlog"
version = "0.0.4"
description = "Implementation of an append-only commit log backed by disk."
repository = "https://github.com/zowens/commitlog"
homepage = "https://github.com/zowens/commitlog"
readme = "README.md"
license = "MIT"

[dependencies]
byteorder = "0.5.3"
crc = "1.3.0"
log = "0.3.6"
memmap = "0.5.0"

[dev-dependencies]
env_logger = "0.3.5"
rand = "0.3"
