[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
description = "Implementation of an append-only commit log backed by disk."
homepage = "https://github.com/zowens/commitlog"
license = "MIT"
name = "commitlog"
readme = "README.md"
repository = "https://github.com/zowens/commitlog"
version = "0.0.10"

[dependencies]
byteorder = "1.0"
crc32c = "0.3"
log = "0.4.1"
memmap = "0.6"

[dev-dependencies]
env_logger = "0.5"
rand = "0.4"
