[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
name = "commitlog"
version = "0.1.0"

[dependencies]
byteorder = "0.5.3"
crc = "1.3.0"
env_logger = "0.3.5"
log = "0.3.6"
memmap = "0.5.0"
rand = "0.3"
